import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Product } from "./types";
import { formatCurrency, formatDateTime } from "./format";
import {
  calcAfterDiscount,
  calcDiscountAmount,
  calcGrandTotal,
} from "./calculations";

/**
 * Generate a professional PDF report for the medicine discount calculation.
 */
export function generatePDF(
  products: Product[],
  discountPercent: number
): void {
  try {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 16;
    let y = 20;

    // ── Header ──
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Medicine Discount Calculator", pageWidth / 2, y, {
      align: "center",
    });
    y += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(
      "Quickly calculate medicine prices and discounts",
      pageWidth / 2,
      y,
      { align: "center" }
    );
    y += 10;

    // Date and time
    const now = new Date();
    const { dateStr, timeStr } = formatDateTime(now);

    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(`Date: ${dateStr}`, margin, y);
    doc.text(`Time: ${timeStr}`, pageWidth - margin, y, { align: "right" });
    y += 4;

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // ── Product Table ──
    const grandTotal = calcGrandTotal(products);

    const tableBody = products.map((p, idx) => [
      (idx + 1).toString(),
      p.name,
      formatCurrency(p.unitPrice),
      p.quantity.toString(),
      formatCurrency(p.total),
      formatCurrency(calcAfterDiscount(p.total, discountPercent)),
    ]);

    autoTable(doc, {
      startY: y,
      head: [
        ["SL", "Product Name", "Unit Price", "Qty", "Total", "After Discount"],
      ],
      body: tableBody,
      foot: [["", "", "", "", "Grand Total", formatCurrency(grandTotal)]],
      theme: "grid",
      margin: { left: margin, right: margin },
      styles: {
        fontSize: 9,
        cellPadding: 3,
        textColor: [30, 30, 30],
        lineColor: [200, 200, 200],
        lineWidth: 0.3,
      },
      headStyles: {
        fillColor: [23, 23, 23],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        halign: "center",
      },
      footStyles: {
        fillColor: [244, 244, 244],
        textColor: [23, 23, 23],
        fontStyle: "bold",
        halign: "right",
      },
      columnStyles: {
        0: { halign: "center", cellWidth: 12 },
        1: { halign: "left" },
        2: { halign: "right", cellWidth: 26 },
        3: { halign: "center", cellWidth: 16 },
        4: { halign: "right", cellWidth: 28 },
        5: { halign: "right", cellWidth: 32 },
      },
    });

    // Get the Y position after the table
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 12;

    // ── Summary Section ──
    const totalDiscount = calcDiscountAmount(grandTotal, discountPercent);
    const finalPayable = grandTotal - totalDiscount;

    const summaryX = margin;
    const valueX = pageWidth - margin;

    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);

    // Summary background
    doc.setFillColor(250, 250, 250);
    doc.rect(margin, y - 4, pageWidth - margin * 2, 44, "F");

    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.setFont("helvetica", "normal");

    // Total Product Price
    doc.text("Total Product Price", summaryX + 4, y + 4);
    doc.text(formatCurrency(grandTotal), valueX - 4, y + 4, {
      align: "right",
    });
    y += 10;

    // Discount
    doc.text("Discount", summaryX + 4, y + 4);
    doc.text(`${discountPercent}%`, valueX - 4, y + 4, { align: "right" });
    y += 10;

    // Discount Amount
    doc.text("Discount Amount", summaryX + 4, y + 4);
    doc.setTextColor(200, 60, 60);
    doc.text(`- ${formatCurrency(totalDiscount)}`, valueX - 4, y + 4, {
      align: "right",
    });
    y += 8;

    // Divider
    doc.setDrawColor(180, 180, 180);
    doc.line(summaryX + 4, y + 2, valueX - 4, y + 2);
    y += 6;

    // Final Payable
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(23, 23, 23);
    doc.text("Final Payable", summaryX + 4, y + 4);
    doc.text(formatCurrency(finalPayable), valueX - 4, y + 4, {
      align: "right",
    });

    // ── Footer ──
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(160, 160, 160);
    doc.text(
      "Generated by Medicine Discount Calculator",
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );

    // Save
    const filename = `medicine-calculation-${dateStr.replace(/\s/g, "-")}.pdf`;
    doc.save(filename);
  } catch (error) {
    console.error("PDF generation error:", error);
    throw new Error("Unable to generate the PDF. Please try again.");
  }
}
